# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/active_link_to/all/active_link_to.rbi
#
# active_link_to-1.0.5

module ActiveLinkTo
  def active_link_to(*args, &block); end
  def active_link_to_class(url, options = nil); end
  def is_active_link?(url, condition = nil); end
end
