# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/after_party/all/after_party.rbi
#
# after_party-1.11.2

module AfterParty
  def self.setup; end
end
class AfterParty::Railtie < Rails::Railtie
end
module AfterParty::TaskRecord::GeneratedAttributeMethods
end
class AfterParty::TaskRecord < ActiveRecord::Base
  def self._validators; end
  def self.attribute_type_decorations; end
  def self.completed_task?(version); end
  def self.defined_enums; end
  def self.page(num = nil); end
  extend Kaminari::ConfigurationMethods::ClassMethods
  include AfterParty::TaskRecord::GeneratedAssociationMethods
  include AfterParty::TaskRecord::GeneratedAttributeMethods
  include Kaminari::ActiveRecordModelExtension
  include Kaminari::ConfigurationMethods
end
module AfterParty::TaskRecord::GeneratedAssociationMethods
end
class AfterParty::TaskRecord::ActiveRecord_Relation < ActiveRecord::Relation
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include AfterParty::TaskRecord::GeneratedRelationMethods
end
module AfterParty::TaskRecord::GeneratedRelationMethods
end
class AfterParty::TaskRecord::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include AfterParty::TaskRecord::GeneratedRelationMethods
end
class AfterParty::TaskRecord::ActiveRecord_AssociationRelation < ActiveRecord::AssociationRelation
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include AfterParty::TaskRecord::GeneratedRelationMethods
end
