# typed: strong
# This is an autogenerated file for Rails' mailers.
# Please rerun bundle exec rake rails_rbi:mailers to regenerate.
class MeetingMailer
  sig { params(meeting_id: T.untyped).returns(ActionMailer::MessageDelivery) }
  def self.attendees_email(meeting_id); end

  sig { returns(ActionMailer::MessageDelivery) }
  def self.inline_images; end

  sig { params(_: T.untyped).returns(ActionMailer::MessageDelivery) }
  def self.inline_images=(_); end
end
