# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 58e92943e535fdbce933f18cddc6b5341b85a0e286f963f68f55b3b6e6281160fb5cff944c76ce4711bda3b5764557ddc30f4102d5e3599e572006483788dedf

test:
  secret_key_base: 0c1a94e4a45d581c56bcd016848881eb86bff3a3e56376c9994ac7e71c20c9ce0806e8155dece0c08dc6a62c28ea82ac7a40462d8f56f3e372e78c841091927f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
