# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: ignore
module ::Anonymous_Delegator_456; end
module ::Anonymous_Delegator_458; end
module ::Anonymous_Delegator_7; end
module ActiveRecord::Associations::CollectionProxy; end
module ActiveStorage::Blob::Analyzable; end
module ActiveStorage::Blob::Identifiable; end
module ActiveStorage::Variant; end
module Agendum::MarkdownRenderer; end
module Rails::Engine::Configuration; end
