# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

# Reference: https://medium.com/@OwenTran/github-workflow-for-rails-ci-34209a53d19e
name: Run Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
       # ruby-version: 2.7.1 # Note: Not needed because we have a .ruby-version file
        bundler-cache: true
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.13.0
    - name: Install dependencies
      run: |
        bundle install
        yarn install
    - name: Build assets
      run: SECRET_KEY_BASE=test bundle exec rake assets:precompile
    - name: Run tests
      env:
        PG_DATABASE: postgres
        PG_HOST: localhost
        PG_USER: postgres
        PG_PASSWORD: password
        RAILS_ENV: test
        DISABLE_SPRING: 1
      run: |
        bin/rails db:setup
        bundle exec rails test && bundle exec rails test:system
